import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { AtlantisVipGeneratedModule, AtlantisVipGeneratedSharedModule } from './generated/module.js';
import { AtlantisVipValidator, AtlantisVipValidationRegistry } from './atlantis-vip-validator.js';
import { AtlantisVipScopeProvider } from './atlantis-vip-scope.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AtlantisVipAddedServices = {
    validation: {
        AtlantisVipValidator: AtlantisVipValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AtlantisVipServices = LangiumServices & AtlantisVipAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AtlantisVipModule: Module<AtlantisVipServices, PartialLangiumServices & AtlantisVipAddedServices> = {
    validation: {
        AtlantisVipValidator: () => new AtlantisVipValidator(),
        ValidationRegistry: (services) => new AtlantisVipValidationRegistry(services)
    },
    references: {
        ScopeProvider: (services) => new AtlantisVipScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAtlantisVipServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    AtlantisVip: AtlantisVipServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AtlantisVipGeneratedSharedModule
    );
    const AtlantisVip = inject(
        createDefaultModule({ shared }),
        AtlantisVipGeneratedModule,
        AtlantisVipModule
    );
    shared.ServiceRegistry.register(AtlantisVip);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, AtlantisVip };
}
